--<ScriptOptions statementTerminator=";"/>

ALTER TABLE Pessoa DROP PRIMARY KEY;

ALTER TABLE Mestre DROP INDEX FK892A760C57283D11;

ALTER TABLE Pessoa_RedeSocial DROP INDEX FK630FFA19270B4066;

ALTER TABLE Pedido_Produto DROP INDEX FK55E4DBFFBE24F9E9;

ALTER TABLE Jogador_Jogo DROP INDEX FK8BAD9B0458B7FE4B;

ALTER TABLE Pedido_Produto DROP INDEX FK55E4DBFF8AB0F16A;

ALTER TABLE Personagem DROP INDEX FK9F4B6C434CED96A9;

ALTER TABLE MesaJogo_Personagem DROP INDEX FK33E09FEFDA74BBA9;

ALTER TABLE Jogador_Jogo DROP INDEX FK8BAD9B044CED96A9;

ALTER TABLE Personagem DROP INDEX FK9F4B6C4358B7FE4B;

ALTER TABLE Pedido_Produto DROP INDEX produtos_id;

ALTER TABLE MesaJogo_Personagem DROP INDEX FK33E09FEF5D31B989;

ALTER TABLE Pedido DROP INDEX FK8E4203654E4AB70B;

ALTER TABLE Pessoa_RedeSocial DROP INDEX FK630FFA19BEE31CA9;

ALTER TABLE Jogador_Jogo DROP INDEX FK8BAD9B04B754346;

DROP TABLE Produto;

DROP TABLE Mestre;

DROP TABLE Pessoa_RedeSocial;

DROP TABLE Pessoa;

DROP TABLE RedeSocial;

DROP TABLE Pedido_Produto;

DROP TABLE Jogador;

DROP TABLE Jogo;

DROP TABLE hibernate_sequence;

DROP TABLE Teste;

DROP TABLE Jogador_Jogo;

DROP TABLE Pedido;

DROP TABLE Personagem;

DROP TABLE MesaJogo_Personagem;

DROP TABLE Cliente;

DROP TABLE MesaJogo;

